### ISSUE TITLE
Implement RFC0009: Remove `yj` binary

### ISSUE THREAD

**Issue by loewenstein** [paketo-buildpacks/rfcs#293]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/stacks/0009-remove-yj.md)

### Summary
Remove the `yj` binary from all stacks' build images

### Stack Adoption
- [x] Jammy Static
- [x] Jammy Tiny
- [x] Jammy Base
- [x] Jammy Full

**Comment by loewenstein** [comment]
Hey @paketo-buildpacks/stacks-maintainers,

here's the implementation tracking issue for the `yj` removal RFC.

**Comment by robdimsdale** [comment]
With the PRs merged above for all jammy stacks, this is complete.

**Comment by sophiewigmore** [comment]
@robdimsdale unfortunately, I think the stack version bumps should have been a minor bump, since we removed a package which could break folks. Do you think we should cut new minor releases to make this clear?

**Comment by robdimsdale** [comment]
@sophiewigmore I think they should either be a major or a patch. Depending on whether you view `yj` as part of the surface area of a stack or not.

I don't, hence the minor. We could could majors if you want though.

**Comment by sophiewigmore** [comment]
Why don't you view it as a part of the surface area of the stack? I think it would be if it was in the stack before! Also, I don't think any of our stacks are at a 1.0.0 release yet, which would make a minor bump the best option IMO

**Comment by robdimsdale** [comment]
Maybe it would be more accurate to say I don't consider the `yj` library part of the _supported_ surface area of the stack.

My understanding is that `yj` was added to help simple shell-based buildpacks interact with TOML files. I don't think anyone actually uses it for that feature as all of our buildpacks have TOML parsing libraries in golang. I view its existence as a bug, not a feature. So I view its removal as a bugfix, not a breaking change.

Also, pre v1.0.0 [semver doesn't really exist](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase), so I interpret that to mean we have flexibility to choose our own versions.

Personally I don't think the majority of Paketo consumers ever look at stack versions because they're always hidden inside a builder.

All of that being said, I don't really feel strongly about this. If you think a minor bump is more clear to consumers, I have no objections to you re-releasing all the stacks with a minor bump.
